### ISSUE TITLE
Error with multicategorical mediator

### ISSUE THREAD

**Issue by olivierISCIII** [jmpsteen/medflex#15]
Dear medflex Team,

I tried to use the weighting-based approach with a multicategorical mediator variable and got the following error:

```
expData <- neWeight(cut(negaff,3) ~ att + gender + educ , family = multinomial(), data = UPBdata, FUN = vgam)
## Error in pred[i, as.character(x[i])] : incorrect number of dimensions
```
The version of `medflex` that I have installed is `0.6-6`.
Best regards.

**Comment by martaczc** [comment]
I have a similar problem.
Here is a working example:

```{r}
library(tidyverse)
library(medflex)
library(VGAM) 

my_data <- tibble(
  mediator = c("a", "b", "c", "b", "c", "c", "a", "a", "b", "b"),
  treatment = c(1, 0, 1, 1, 0, 1, 0, 0, 0, 1),
  outcome = c(0, 0, 1, 1, 1, 0, 1, 0, 1, 0)
)

model_w <- vglm(
  mediator ~ factor(treatment),
  data = my_data,
  family = multinomial
)

my_data_exp <- neWeight(model_w)
# Error in pred[i, as.character(x[i])] : incorrect number of dimensions
```
I use medflex 0.6-7 and VGAM 1.1-5

**Comment by jmpsteen** [comment]
Thanks for your interest in medflex! This issue should be fixed now in the latest development release 0.6-8 available from github (by a simple `,` :-)). The working example used to work in an older version of the package, but due to some changes along with insufficient testing, the updated code no longer seemed to be compatible with multinomial regression using `vglm`.

@olivierISCIII Please note that the first working example provided does not work due to use of the `cut` function in the `formula` argument. Medflex only handles the functions `factor` and some other convenience functions for modelling (e.g. splines or polynomials in `neImpute`). So please first recode this variable as below. With these changes your code should work.

```
UPBdata$negaffcat <- cut(UPBdata$negaff, 3)
expData <- neWeight(negaffcat ~ att + gender + educ , family = multinomial(), data = UPBdata, FUN = vgam)
```

Please close this issue if you agree it has been fixed and the working example runs without errors.

**Comment by anhthyngo** [comment]
> Thanks for your interest in medflex! This issue should be fixed now in the latest development release 0.6-8 available from github (by a simple `,` :-)). The working example used to work in an older version of the package, but due to some changes along with insufficient testing, the updated code no longer seemed to be compatible with multinomial regression using `vglm`.
> 
> @olivierISCIII Please note that the first working example provided does not work due to use of the `cut` function in the `formula` argument. Medflex only handles the functions `factor` and some other convenience functions for modelling (e.g. splines or polynomials in `neImpute`). So please first recode this variable as below. With these changes your code should work.
> 
> ```
> UPBdata$negaffcat <- cut(UPBdata$negaff, 3)
> expData <- neWeight(negaffcat ~ att + gender + educ , family = multinomial(), data = UPBdata, FUN = vgam)
> ```
> 
> Please close this issue if you agree it has been fixed and the working example runs without errors.

Hi I'm still getting 'Error in prep[i, as.character(x[i])] : incorrect number of dimensions' when running this line of code

```
UPBdata$negaffcat <- cut(UPBdata$negaff, 3)
expData <- neWeight(negaffcat ~ att + gender + educ , family = multinomial(), data = UPBdata, FUN = vgam)

```

**Comment by anhthyngo** [comment]
> I have a similar problem. Here is a working example:
> 
> ```
> library(tidyverse)
> library(medflex)
> library(VGAM) 
> 
> my_data <- tibble(
>   mediator = c("a", "b", "c", "b", "c", "c", "a", "a", "b", "b"),
>   treatment = c(1, 0, 1, 1, 0, 1, 0, 0, 0, 1),
>   outcome = c(0, 0, 1, 1, 1, 0, 1, 0, 1, 0)
> )
> 
> model_w <- vglm(
>   mediator ~ factor(treatment),
>   data = my_data,
>   family = multinomial
> )
> 
> my_data_exp <- neWeight(model_w)
> # Error in pred[i, as.character(x[i])] : incorrect number of dimensions
> ```
> 
> I use medflex 0.6-7 and VGAM 1.1-5

Were you able to resolve this?

**Comment by olivierISCIII** [comment]
It works fine for me, using version 0.6-8. Thanks.
